### PR TITLE
Added navbar and masthead for event page.

### PR DESCRIPTION
**Pull request by rtnpro**
Start using bootstrap to beautify flock-registration pages. This is just some initial work. Please let me know whether I shall continue improving the entire UI in a similar way.

FYI, I am no designer, but I can make web apps like https://www.waartaa.com/.

### CODE REVIEW

**Comment by lmacken** [comment]
Thanks for the pull request, I'm definitely in favor of cleaning up the UI.

I pushed your change to https://flocktest-lmacken.rhcloud.com - the only problem I see so far is that there is a gap between the header and then subheader.

**Comment by rtnpro** [comment]
@lmacken I will fix that :)

**Comment by rtnpro** [comment]
@lmacken  I have updated this pull request. Please give it a try. If it's OK, you can merge this. I will keep working on this branch and send other similar PRs.

**Comment by lmacken** [comment]
Looks good to me, thanks!

**Pull request merged**
